# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
                ('sequence', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodExceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('add_day', models.BooleanField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Period')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Period')),
            ],
        ),
        migrations.CreateModel(
            name='TrainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.FilePathField(path='/media/lucidiot/ROUCHETDA2I/Projet/TchouTchouGo/main/static/main/img')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='traintype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TrainType'),
        ),
        migrations.AddField(
            model_name='halt',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Station'),
        ),
        migrations.AddField(
            model_name='halt',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Train'),
        ),
    ]
