# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('end_halt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Halt')),
                ('start_halt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Halt')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('passengers', models.PositiveSmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='PeriodExceptions',
            new_name='PeriodException',
        ),
        migrations.AddField(
            model_name='traintype',
            name='km_price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Travel'),
        ),
    ]
